spring.application.name=backend
server.port=8000
spring.datasource.url=jdbc:postgresql://localhost:5432/Aegiscode
spring.datasource.username=postgres
spring.datasource.password=Pandey@1806

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

jwt.secret=yourVeryLongSecretKeyForAegisCode2026SuperSecureKey
jwt.expiration=86400000

# Groq API Configuration
groq.api.key=${GROQ_API_KEY:your_groq_api_key_here}

# GitHub OAuth Configuration
github.client.id=${GITHUB_CLIENT_ID:Ov23li4KyHViXCgtlefM}
github.client.secret=${GITHUB_CLIENT_SECRET:c562bf94e3977d6d8fc95607d833e5f33fbc0c5e}
github.redirect.uri=${GITHUB_REDIRECT_URI:http://localhost:5173/auth/github/callback}