spring.application.name=backend
server.port=8000
spring.datasource.url=jdbc:postgresql://localhost:5432/Aegiscode
spring.datasource.username=postgres
spring.datasource.password=Pandey@1806

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=yourVeryLongSecretKeyForAegisCode2026SuperSecureKey
jwt.expiration=86400000