spring.application.name=backend
server.port=${PORT:8000}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Aegiscode}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pandey@1806}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

jwt.secret=${JWT_SECRET:c4f8d9b2a7e1f365829104b9381c620478a51e92d64f0b83e712a95d036128fa}
jwt.expiration=86400000

# Groq API Configuration
groq.api.key=${GROQ_API_KEY:your_groq_api_key_here}

# Frontend & GitHub OAuth Configuration
frontend.url=${FRONTEND_URL:https://aegis-code-42f9ufijc-myself-8035.vercel.app}
github.client.id=${GITHUB_CLIENT_ID:Ov23li4KyHViXCgtlefM}
github.client.secret=${GITHUB_CLIENT_SECRET:c562bf94e3977d6d8fc95607d833e5f33fbc0c5e}
github.redirect.uri=${GITHUB_REDIRECT_URI:${frontend.url}/auth/github/callback}